### ISSUE TITLE
Referencing the file twice will copy it again

### ISSUE THREAD

**Issue by edisongustavo** [gabrielcnr/pytest-datadir#8]
I've noticed that on every call to `datadir.__getitem__` the file is always "re-copied".

This is a problem in my opinion since my first impression of calling `__getitem__`  is that only the path of the file is returned, not copied again.

**Comment by nicoddemus** [comment]
I agree that's surprising and a bug.

Please also take a look at the discussion in #7... we might change the API entirely and get rid of this kind of implicit behavior by making `datadir` return a `Path` object instead.

**Comment by gabrielcnr** [comment]
@edisongustavo @nicoddemus What's the behaviour you'd expect to see here? If the file already exists in the temp data dir, then simply don't do anything. Or something different? For example if the file already exists, check if it's the same contents (based on hash?) and copy the file over again?

I believe I've never noticed this because in 99% of the cases I use the test data file only once in a test. I understand this current behaviour is not desired, especially if you have large files (e.g.: big hdf5 or binary files)  because that would add an overhead to the execution of the test.

How can we be defensive against changes made to the test file in a test (writing to the test file, for example)?

**Comment by nicoddemus** [comment]
IMHO we should ditch the current copy-on-access behavior altogether... it is just not easy to implement a solution which will work all the time. Usually the test files are not that big (after all they are commited in the repository), and if someone needs to handle that case for a single test they can use `original_datadir` directly and handle that themselves; but I think this is rare enough to not provide something out of the box right now, although I see we can study how to add this feature in the future.

**Comment by gabrielcnr** [comment]
Following the discussion I had offline with @nicoddemus I believe we have agreed the following:

1. The `datadir` fixture is going to be used on the common case. When the fixture is created (i.e., before each test that uses it) it will make a copy from the entire original data directory into a temporary one. This is the safest approach. For the average case, the performance overhead caused by this operation will be minimal.

1. The `original_datadir` fixture (yet to be implemented) can be used to directly access the files in original data directory. It will not make any copies, this it's going to present a better performance. If the user writes to the files, this will likely to break subsequent tests. But at least the usage of the fixture is going to be explicit and we will have this properly documented in the official docs.

**Comment by nicoddemus** [comment]
@edisongustavo @gqmelo what you guys think?

**Comment by gqmelo** [comment]
Looks good, it will make much easier to use

**Comment by nicoddemus** [comment]
With `1.0` the behavior above was implemented so this can now be closed. Thanks everyone for the discussion!
